---
- name: Copy kickstart template
  template: src=base.ks.j2 dest=/tmp/base.ks

- name: Create image file
  qemu_img: dest={{ poolpath }}/{{ initimage }}.qcow2 size={{ initdisksize }} format=qcow2 opt=preallocation=metadata state=present

- name: Kick off the virt-install
  shell: virt-install --connect=qemu:///system
           --network network:default
           --initrd-inject=/tmp/base.ks
           --extra-args="ks=file:/base.ks ksdevice=eth0 keymap=us lang=en_US {{ ks_extra_args }}"
           --name={{ initimage }}
           --location={{ install_url }}
           --disk {{ poolpath }}/{{ initimage }}.qcow2,format=qcow2
           --ram {{ initmemsize }}
           --vcpus 2
           --cpu host
           --hvm
           --os-variant {{ os_variant }}
           --vnc
           --noreboot
           --wait=-1
           creates=/etc/libvirt/qemu/{{ initimage }}.xml
  register: vm_create

- name: Pause for a bit to let the node finish shutdown
  pause: seconds=15
