---
- hosts: vm_host
  remote_user: "{{ remote_user }}"
  sudo: yes
  roles:
    - { role: common }
    - { role: ntp }
    - { role: packages }
    - { role: security }
    - { role: libvirt }
    - { role: networks }
    - { role: nfs-setup }
    - { role: ssh-keys }
    - { role: kickstart }
    - { role: setup-guests }
    - { role: generate-inventory }
    - { role: setup-khaleesi }
    - { role: reset-vms-script }

- hosts: clients
  remote_user: "{{ remote_user_client }}"
  sudo: yes
  roles:
    - { role: client-config }

- include: snapshot.yml
