---
- name: Host dependencies
  yum: name={{ item }} state=latest
  with_items:
    - nfs-utils
    - qemu-kvm
    - spice-server
    - qemu-img
    - libguestfs-tools
    - libvirt
    - virt-manager
    - git
    - tigervnc-server
    - tigervnc-server-module
    - tigervnc
    - xorg-x11-twm
    - xorg-x11-server-utils
    - emacs-nox
    - virt-viewer
    - nc
    - git-review
    - python-virtualenv

- name: Install additional RHEL packages
  yum: name={{ item }} state=latest
  with_items:
    - ncat
    - python-virtinst
  when: ansible_distribution == 'RedHat'

- name: Install additional Fedora packages
  yum: name={{ item }} state=latest
  with_items:
    - nmap-ncat
    - virt-install
  when: ansible_distribution == 'Fedora'

