---
- name: Default network xml
  template: src=default-network.xml.j2 dest=/tmp/default-network.xml

- name: Is default network already changed?
  shell: virsh net-dumpxml default | grep {{ default_ip_prefix }}
  ignore_errors: True
  register: default_network_changed

- name: Change default network ip
  script: default_network_ip.sh
  when: default_network_changed|failed

- name: Create foreman network xml
  template: src={{ item[0] }}.xml.j2 dest=/tmp/{{ item[0] }}_{{ item[1] }}.xml
  with_nested:
    - network_names
    - network_numbers

- name: Create foreman networks
  script: create_networks.sh {{ item[0] }} {{ item[1] }}
  with_nested:
    - network_names
    - network_numbers

